version: "3.1"

services:
  web:
    build: .
    image: banbot:dev
    ports:
      - 8080:8080
    volumes:
      - .:/src
    command: yarn dev
    environment:
      - MONGO_URI=mongodb://p4nth3rb0t:supersecretpassword@mongo:27017/banbot

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: p4nth3rb0t
      MONGO_INITDB_ROOT_PASSWORD: supersecretpassword

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: p4nth3rb0t
      ME_CONFIG_MONGODB_ADMINPASSWORD: supersecretpassword
